In [30]:
import pandas as pd

match_info = pd.read_csv("../data/raw/Match_Info.csv")
ball_by_ball = pd.read_csv("../data/raw/Ball_By_Ball_Match_Data.csv")
match_info.head()

,match_number,team1,team2,match_date,toss_winner,toss_decision,result,eliminator,winner,player_of_match,venue,city,team1_players,team2_players
0,336036,Rajasthan Royals,Mumbai Indians,2008-05-26,Rajasthan Royals,field,Win,NaN,Rajasthan Royals,Sohail Tanvir,Sawai Mansingh Stadium,Jaipur,"Kamran Akmal, SA Asnodkar, YK Pathan, SR Watso...","ST Jayasuriya, SR Tendulkar, AM Nayar, RV Utha..."
1,335995,Kings XI Punjab,Delhi Daredevils,2008-04-27,Delhi Daredevils,bat,Win,NaN,Kings XI Punjab,SM Katich,"Punjab Cricket Association Stadium, Mohali",Chandigarh,"K Goel, SM Katich, KC Sangakkara, DPMD Jayawar...","G Gambhir, V Sehwag, S Dhawan, Shoaib Malik, M..."
2,1254108,Royal Challengers Bangalore,Mumbai Indians,2021-09-26,Mumbai Indians,field,Win,NaN,Royal Challengers Bangalore,GJ Maxwell,Dubai International Cricket Stadium,Dubai,"V Kohli, D Padikkal, KS Bharat, GJ Maxwell, AB...","RG Sharma, Q de Kock, Ishan Kishan, SA Yadav, ..."
3,829761,Kolkata Knight Riders,Delhi Daredevils,2015-05-07,Kolkata Knight Riders,bat,Win,NaN,Kolkata Knight Riders,PP Chawla,Eden Gardens,Kolkata,"RV Uthappa, G Gambhir, MK Pandey, PP Chawla, Y...","MK Tiwary, SS Iyer, JP Duminy, KM Jadhav, Yuvr..."
4,1216521,Chennai Super Kings,Mumbai Indians,2020-10-23,Mumbai Indians,field,Win,NaN,Mumbai Indians,TA Boult,Sharjah Cricket Stadium,NaN,"RD Gaikwad, F du Plessis, AT Rayudu, N Jagadee...","Q de Kock, Ishan Kishan, SA Yadav, SS Tiwary, ..."

In [31]:
ball_by_ball.head()

,ID,Innings,Overs,BallNumber,Batter,Bowler,NonStriker,ExtraType,BatsmanRun,ExtrasRun,TotalRun,IsWicketDelivery,PlayerOut,Kind,FieldersInvolved,BattingTeam
0,336036,1,0,1,ST Jayasuriya,Sohail Tanvir,SR Tendulkar,NaN,0,0,0,0,NaN,NaN,NaN,Mumbai Indians
1,336036,1,0,2,ST Jayasuriya,Sohail Tanvir,SR Tendulkar,NaN,0,0,0,0,NaN,NaN,NaN,Mumbai Indians
2,336036,1,0,3,ST Jayasuriya,Sohail Tanvir,SR Tendulkar,NaN,0,0,0,0,NaN,NaN,NaN,Mumbai Indians
3,336036,1,0,4,ST Jayasuriya,Sohail Tanvir,SR Tendulkar,NaN,0,0,0,0,NaN,NaN,NaN,Mumbai Indians
4,336036,1,0,5,ST Jayasuriya,Sohail Tanvir,SR Tendulkar,wides,0,1,1,0,NaN,NaN,NaN,Mumbai Indians

In [32]:
match_info.columns

Index(['match_number', 'team1', 'team2', 'match_date', 'toss_winner',
       'toss_decision', 'result', 'eliminator', 'winner', 'player_of_match',
       'venue', 'city', 'team1_players', 'team2_players'],
      dtype='str')

In [33]:
ball_by_ball.columns

Index(['ID', 'Innings', 'Overs', 'BallNumber', 'Batter', 'Bowler',
       'NonStriker', 'ExtraType', 'BatsmanRun', 'ExtrasRun', 'TotalRun',
       'IsWicketDelivery', 'PlayerOut', 'Kind', 'FieldersInvolved',
       'BattingTeam'],
      dtype='str')

In [34]:
match_info["result"].unique()

<StringArray>
['Win', 'no result', 'tie']
Length: 3, dtype: str

In [35]:
match_info["result"].value_counts(dropna=False)

result
Win          1146
tie            15
no result       8
Name: count, dtype: int64

In [36]:
match_info["result"].nunique()

3

In [37]:
match_info["winner"].isna().sum()

np.int64(23)

In [38]:
match_info["winner"].value_counts(dropna=False)

winner
Mumbai Indians                 151
Chennai Super Kings            142
Kolkata Knight Riders          135
Rajasthan Royals               114
Royal Challengers Bangalore    114
Sunrisers Hyderabad             93
Kings XI Punjab                 85
Delhi Daredevils                67
Delhi Capitals                  51
Gujarat Titans                  37
Punjab Kings                    34
Lucknow Super Giants            30
Deccan Chargers                 29
NaN                             23
Royal Challengers Bengaluru     18
Gujarat Lions                   13
Pune Warriors                   12
Rising Pune Supergiant          10
Kochi Tuskers Kerala             6
Rising Pune Supergiants          5
Name: count, dtype: int64

In [39]:
match_info["eliminator"].isna().sum()

np.int64(1154)

In [40]:
match_info["eliminator"].value_counts(dropna=False)

eliminator
NaN                            1154
Delhi Capitals                    4
Kings XI Punjab                   3
Rajasthan Royals                  2
Royal Challengers Bangalore       2
Mumbai Indians                    2
Kolkata Knight Riders             1
Sunrisers Hyderabad               1
Name: count, dtype: int64

In [41]:
match_info.groupby("result")["winner"].apply(lambda x: x.isna().sum())

result
Win           0
no result     8
tie          15
Name: winner, dtype: int64

In [42]:
match_info.groupby("result")["eliminator"].apply(lambda x: x.notna().sum())

result
Win           0
no result     0
tie          15
Name: eliminator, dtype: int64

In [43]:
match_info[match_info["result"] == "tie"][["match_number", "team1", "team2", "winner", "eliminator"]].head(10)

,match_number,team1,team2,winner,eliminator
131,392190,Kolkata Knight Riders,Rajasthan Royals,NaN,Rajasthan Royals
361,1216517,Mumbai Indians,Kings XI Punjab,NaN,Kings XI Punjab
409,1175365,Kolkata Knight Riders,Delhi Capitals,NaN,Delhi Capitals
432,829741,Rajasthan Royals,Kings XI Punjab,NaN,Kings XI Punjab
433,1216512,Kolkata Knight Riders,Sunrisers Hyderabad,NaN,Kolkata Knight Riders
490,1216547,Royal Challengers Bangalore,Mumbai Indians,NaN,Royal Challengers Bangalore
496,1216493,Delhi Capitals,Kings XI Punjab,NaN,Delhi Capitals
531,419121,Chennai Super Kings,Kings XI Punjab,NaN,Kings XI Punjab
594,729315,Kolkata Knight Riders,Rajasthan Royals,NaN,Rajasthan Royals
821,1254077,Delhi Capitals,Sunrisers Hyderabad,NaN,Delhi Capitals

In [44]:
match_info[match_info["result"] == "tie"][["match_number", "team1", "team2", "winner", "eliminator"]].head(10)

,match_number,team1,team2,winner,eliminator
131,392190,Kolkata Knight Riders,Rajasthan Royals,NaN,Rajasthan Royals
361,1216517,Mumbai Indians,Kings XI Punjab,NaN,Kings XI Punjab
409,1175365,Kolkata Knight Riders,Delhi Capitals,NaN,Delhi Capitals
432,829741,Rajasthan Royals,Kings XI Punjab,NaN,Kings XI Punjab
433,1216512,Kolkata Knight Riders,Sunrisers Hyderabad,NaN,Kolkata Knight Riders
490,1216547,Royal Challengers Bangalore,Mumbai Indians,NaN,Royal Challengers Bangalore
496,1216493,Delhi Capitals,Kings XI Punjab,NaN,Delhi Capitals
531,419121,Chennai Super Kings,Kings XI Punjab,NaN,Kings XI Punjab
594,729315,Kolkata Knight Riders,Rajasthan Royals,NaN,Rajasthan Royals
821,1254077,Delhi Capitals,Sunrisers Hyderabad,NaN,Delhi Capitals

In [45]:
sorted(match_info["team1"].unique())

['Chennai Super Kings',
 'Deccan Chargers',
 'Delhi Capitals',
 'Delhi Daredevils',
 'Gujarat Lions',
 'Gujarat Titans',
 'Kings XI Punjab',
 'Kochi Tuskers Kerala',
 'Kolkata Knight Riders',
 'Lucknow Super Giants',
 'Mumbai Indians',
 'Pune Warriors',
 'Punjab Kings',
 'Rajasthan Royals',
 'Rising Pune Supergiant',
 'Rising Pune Supergiants',
 'Royal Challengers Bangalore',
 'Royal Challengers Bengaluru',
 'Sunrisers Hyderabad']

In [46]:
sorted(match_info["team2"].unique())

['Chennai Super Kings',
 'Deccan Chargers',
 'Delhi Capitals',
 'Delhi Daredevils',
 'Gujarat Lions',
 'Gujarat Titans',
 'Kings XI Punjab',
 'Kochi Tuskers Kerala',
 'Kolkata Knight Riders',
 'Lucknow Super Giants',
 'Mumbai Indians',
 'Pune Warriors',
 'Punjab Kings',
 'Rajasthan Royals',
 'Rising Pune Supergiant',
 'Rising Pune Supergiants',
 'Royal Challengers Bangalore',
 'Royal Challengers Bengaluru',
 'Sunrisers Hyderabad']

In [47]:
team_names = {
    "Delhi Daredevils": "Delhi Capitals",
    "Kings XI Punjab": "Punjab Kings",
    "Royal Challengers Bangalore": "Royal Challengers Bengaluru",
    "Rising Pune Supergiant": "Rising Pune Supergiants"
}

In [48]:
print(match_info[match_info["result"] == "tie"][["team1", "team2", "winner", "eliminator"]])

'''for index, row in match_info.iterrows():
    if row["result"] == "tie":
        if row["team1"] == row["eliminator"]:
            winner = row["team2"]
            print(winner)
        elif row["team2"] == row["eliminator"]:
            winner = row["team1"]
            print(winner)'''

                            team1                        team2 winner  \
131         Kolkata Knight Riders             Rajasthan Royals    NaN
361                Mumbai Indians              Kings XI Punjab    NaN
409         Kolkata Knight Riders               Delhi Capitals    NaN
432              Rajasthan Royals              Kings XI Punjab    NaN
433         Kolkata Knight Riders          Sunrisers Hyderabad    NaN
490   Royal Challengers Bangalore               Mumbai Indians    NaN
496                Delhi Capitals              Kings XI Punjab    NaN
531           Chennai Super Kings              Kings XI Punjab    NaN
594         Kolkata Knight Riders             Rajasthan Royals    NaN
821                Delhi Capitals          Sunrisers Hyderabad    NaN
845                Mumbai Indians          Sunrisers Hyderabad    NaN
886           Sunrisers Hyderabad  Royal Challengers Bangalore    NaN
917                 Gujarat Lions               Mumbai Indians    NaN
1000  Royal Challengers Bangalore             Delhi Daredevils    NaN
1117               Delhi Capitals             Rajasthan Royals    NaN

                       eliminator
131              Rajasthan Royals
361               Kings XI Punjab
409                Delhi Capitals
432               Kings XI Punjab
433         Kolkata Knight Riders
490   Royal Challengers Bangalore
496                Delhi Capitals
531               Kings XI Punjab
594              Rajasthan Royals
821                Delhi Capitals
845                Mumbai Indians
886           Sunrisers Hyderabad
917                Mumbai Indians
1000  Royal Challengers Bangalore
1117               Delhi Capitals

'for index, row in match_info.iterrows():\n    if row["result"] == "tie":\n        if row["team1"] == row["eliminator"]:\n            winner = row["team2"]\n            print(winner)\n        elif row["team2"] == row["eliminator"]:\n            winner = row["team1"]\n            print(winner)'

result == "Win" → use winner column directly
result == "tie" → winner is whichever of team1/team2 is not in eliminator
result == "no result" → exclude from training

In [49]:
match_info.isnull().sum()

match_number          0
team1                 0
team2                 0
match_date            0
toss_winner           0
toss_decision         0
result                0
eliminator         1154
winner               23
player_of_match       0
venue                 0
city                 51
team1_players         0
team2_players         0
dtype: int64

In [50]:
ball_by_ball.isnull().sum()

ID                       0
Innings                  0
Overs                    0
BallNumber               0
Batter                   0
Bowler                   0
NonStriker               0
ExtraType           263072
BatsmanRun               0
ExtrasRun                0
TotalRun                 0
IsWicketDelivery         0
PlayerOut           264382
Kind                264382
FieldersInvolved    268192
BattingTeam              0
dtype: int64

In [51]:
ball_by_ball["Batter"].unique()[:75]

<StringArray>
[   'ST Jayasuriya',     'SR Tendulkar',         'AM Nayar',
       'RV Uthappa',         'DR Smith',       'SM Pollock',
        'MK Pandey',      'YV Takawale',          'RR Raje',
     'Kamran Akmal',      'SA Asnodkar',        'YK Pathan',
        'SR Watson',           'M Kaif',         'NK Patel',
        'RA Jadeja',        'G Gambhir',         'V Sehwag',
         'S Dhawan',     'Shoaib Malik',        'MK Tiwary',
       'KD Karthik',         'R Bhatia',      'MF Maharoof',
        'VY Mahesh',           'K Goel',        'SM Katich',
    'KC Sangakkara', 'DPMD Jayawardene',     'Yuvraj Singh',
    'TM Srivastava',        'IK Pathan',            'B Lee',
          'V Kohli',       'D Padikkal',        'KS Bharat',
       'GJ Maxwell',   'AB de Villiers',    'Shahbaz Ahmed',
     'DT Christian',      'KA Jamieson',        'RG Sharma',
        'Q de Kock',     'Ishan Kishan',         'SA Yadav',
        'KH Pandya',       'KA Pollard',        'HH Pandya',
        'RD Chahar',        'JJ Bumrah',         'TA Boult',
         'AF Milne',        'PP Chawla',       'AD Russell',
          'J Botha',          'SS Iyer',        'JP Duminy',
        'KM Jadhav',       'AD Mathews',        'SS Tiwary',
        'JA Morkel',       'RD Gaikwad',        'AT Rayudu',
     'F du Plessis',     'N Jagadeesan',         'MS Dhoni',
        'SM Curran',        'DL Chahar',        'SN Thakur',
      'Imran Tahir',         'AJ Finch',         'KL Rahul',
        'DA Warner',        'DJG Sammy',          'NV Ojha']
Length: 75, dtype: str

In [52]:
match_info[match_info["city"].isnull()][["venue", "city"]]

                                    venue city
4                 Sharjah Cricket Stadium  NaN
9     Dubai International Cricket Stadium  NaN
13    Dubai International Cricket Stadium  NaN
22    Dubai International Cricket Stadium  NaN
57                Sharjah Cricket Stadium  NaN
74    Dubai International Cricket Stadium  NaN
79    Dubai International Cricket Stadium  NaN
83    Dubai International Cricket Stadium  NaN
87    Dubai International Cricket Stadium  NaN
143   Dubai International Cricket Stadium  NaN
205   Dubai International Cricket Stadium  NaN
228               Sharjah Cricket Stadium  NaN
247   Dubai International Cricket Stadium  NaN
253   Dubai International Cricket Stadium  NaN
280               Sharjah Cricket Stadium  NaN
283   Dubai International Cricket Stadium  NaN
330               Sharjah Cricket Stadium  NaN
359   Dubai International Cricket Stadium  NaN
361   Dubai International Cricket Stadium  NaN
381               Sharjah Cricket Stadium  NaN
382   Dubai International Cricket Stadium  NaN
468   Dubai International Cricket Stadium  NaN
490   Dubai International Cricket Stadium  NaN
496   Dubai International Cricket Stadium  NaN
509               Sharjah Cricket Stadium  NaN
548   Dubai International Cricket Stadium  NaN
564               Sharjah Cricket Stadium  NaN
566   Dubai International Cricket Stadium  NaN
617   Dubai International Cricket Stadium  NaN
619               Sharjah Cricket Stadium  NaN
628   Dubai International Cricket Stadium  NaN
647               Sharjah Cricket Stadium  NaN
673               Sharjah Cricket Stadium  NaN
680               Sharjah Cricket Stadium  NaN
710   Dubai International Cricket Stadium  NaN
713   Dubai International Cricket Stadium  NaN
732   Dubai International Cricket Stadium  NaN
747   Dubai International Cricket Stadium  NaN
762               Sharjah Cricket Stadium  NaN
783               Sharjah Cricket Stadium  NaN
787   Dubai International Cricket Stadium  NaN
791   Dubai International Cricket Stadium  NaN
809   Dubai International Cricket Stadium  NaN
835               Sharjah Cricket Stadium  NaN
884               Sharjah Cricket Stadium  NaN
926   Dubai International Cricket Stadium  NaN
928               Sharjah Cricket Stadium  NaN
1053  Dubai International Cricket Stadium  NaN
1134  Dubai International Cricket Stadium  NaN
1151              Sharjah Cricket Stadium  NaN
1159  Dubai International Cricket Stadium  NaN

In [53]:
stadium_mapping = {
    "Dubai International Cricket Stadium": "Dubai",
    "Sharjah Cricket Stadium": "Sharjah"
}
#audit that we can give these stadiums city because of the venue

In [54]:
print(match_info["team1_players"].iloc[0])
#we figured out that the match_info players follow the same naming convention as the ball_by_ball players

Kamran Akmal, SA Asnodkar, YK Pathan, SR Watson, M Kaif, RA Jadeja, NK Patel, SK Warne, Sohail Tanvir, SK Trivedi, Pankaj Singh

In [55]:
tie_mask = match_info["result"] == "tie"
match_info.loc[tie_mask, "eliminator"] == match_info.loc[tie_mask, "team1"]

131     False
361     False
409     False
432     False
433      True
490      True
496      True
531     False
594     False
821      True
845      True
886      True
917     False
1000     True
1117     True
dtype: bool

In [56]:
import pandas as pd
df = pd.read_csv("../data/processed/match_info_clean.csv")

print(df.shape)                          # should be 1161 rows (1169 - 8 no results)
print(df["team1"].unique())              # should have no old team names
print(df["city"].isna().sum())           # should be 0
print(df["winner"].isna().sum())         # should be 0
print(df["result"].value_counts())       # should have no "no result"

(1161, 14)
<StringArray>
[           'Rajasthan Royals',                'Punjab Kings',
 'Royal Challengers Bengaluru',       'Kolkata Knight Riders',
         'Chennai Super Kings',              'Delhi Capitals',
              'Mumbai Indians',         'Sunrisers Hyderabad',
        'Lucknow Super Giants',             'Deccan Chargers',
              'Gujarat Titans',               'Pune Warriors',
     'Rising Pune Supergiants',               'Gujarat Lions',
        'Kochi Tuskers Kerala']
Length: 15, dtype: str
0
0
result
Win    1146
tie      15
Name: count, dtype: int64

In [62]:
import pandas as pd
import numpy as np
df = pd.read_csv("../data/processed/match_info_clean.csv")
df["match_date"] = pd.to_datetime(df["match_date"])

team_rows = pd.unique(pd.concat([df["team1"], df["team2"]]))
for team in team_rows:
    chron_matches = df[(df["team1"] == team) | (df["team2"] == team)].sort_values("match_date")
    win_series = (chron_matches["winner"] == team).astype(int)
    chron_matches = chron_matches.copy()
    chron_matches["win"] = win_series
    venue_win_rate = chron_matches.groupby("venue")["win"].expanding().mean().shift(1)
    print(venue_win_rate)

venue
Arun Jaitley Stadium              47           NaN
                                  306     0.000000
Arun Jaitley Stadium, Delhi       1113    0.000000
                                  197     0.000000
                                  528     0.500000
                                            ...
Wankhede Stadium, Mumbai          1076    0.444444
                                  517     0.500000
                                  300     0.454545
Zayed Cricket Stadium, Abu Dhabi  241     0.500000
                                  518     0.000000
Name: win, Length: 233, dtype: float64
venue
Arun Jaitley Stadium              91           NaN
                                  233     1.000000
Arun Jaitley Stadium, Delhi       246     0.500000
Barabati Stadium                  1119    1.000000
                                  732     0.000000
                                            ...
Wankhede Stadium, Mumbai          959     0.250000
                                  1076    0.400000
                                  36      0.333333
                                  588     0.428571
Zayed Cricket Stadium, Abu Dhabi  400     0.500000
Name: win, Length: 262, dtype: float64
venue
Arun Jaitley Stadium                                                   29           NaN
                                                                       875     1.000000
Arun Jaitley Stadium, Delhi                                            1148    0.500000
                                                                       428     0.000000
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow  243     0.500000
                                                                                 ...
Wankhede Stadium, Mumbai                                               841     0.833333
                                                                       471     0.714286
                                                                       116     0.625000
Zayed Cricket Stadium, Abu Dhabi                                       692     0.666667
                                                                       573     0.000000
Name: win, Length: 267, dtype: float64
venue
Arun Jaitley Stadium              998         NaN
                                  406    0.000000
Arun Jaitley Stadium, Delhi       797    0.500000
                                  917    0.000000
                                  856    0.500000
                                           ...
Wankhede Stadium, Mumbai          273    0.428571
                                  773    0.500000
Zayed Cricket Stadium, Abu Dhabi  692    0.444444
                                  247    1.000000
                                  265    1.000000
Name: win, Length: 263, dtype: float64
venue
Arun Jaitley Stadium              699          NaN
                                  950     0.000000
Arun Jaitley Stadium, Delhi       1091    0.500000
                                  596     1.000000
                                  1070    0.500000
                                            ...
Wankhede Stadium, Mumbai          1041    0.444444
                                  1089    0.500000
                                  37      0.545455
Zayed Cricket Stadium, Abu Dhabi  265     0.500000
                                  518     1.000000
Name: win, Length: 251, dtype: float64
venue
Arun Jaitley Stadium              91          NaN
                                  998    0.000000
                                  47     0.500000
                                  629    0.666667
                                  29     0.500000
                                           ...
Wankhede Stadium, Mumbai          363    0.500000
                                  682    0.428571
                                  474    0.375000
                                  727    0.333333
Zayed Cricket Stadium, Abu Dhabi  241    0.300000
Name: win, Length: 263, dtype: float64
venue
Arun Jaitley Stadium              551          NaN
                                  726     0.000000
Arun Jaitley Stadium, Delhi       1113    0.500000
                                  596     1.000000
                                  475     1.000000
                                            ...
Wankhede Stadium, Mumbai          34      0.608696
                                  727     0.583333
Zayed Cricket Stadium, Abu Dhabi  247     0.600000
                                  400     0.000000
                                  1082    0.500000
Name: win, Length: 277, dtype: float64
venue
Arun Jaitley Stadium              629          NaN
                                  1149    1.000000
Arun Jaitley Stadium, Delhi       1091    1.000000
                                  197     0.000000
                                  23      0.000000
                                            ...
Wankhede Stadium, Mumbai          165     0.250000
                                  211     0.200000
                                  70      0.166667
Zayed Cricket Stadium, Abu Dhabi  573     0.142857
                                  1082    1.000000
Name: win, Length: 195, dtype: float64
venue
Arun Jaitley Stadium, Delhi                                            1047         NaN
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow  999     0.000000
                                                                       252     1.000000
                                                                       1132    1.000000
                                                                       298     0.666667
                                                                       243     0.500000
                                                                       607     0.400000
                                                                       1056    0.500000
                                                                       1134    0.571429
                                                                       721     0.625000
                                                                       390     0.555556
                                                                       589     0.600000
                                                                       16      0.545455
                                                                       636     0.583333
                                                                       996     0.538462
                                                                       20      0.500000
                                                                       288     0.533333
                                                                       416     0.562500
                                                                       1118    0.529412
                                                                       155     0.500000
                                                                       296     0.473684
Brabourne Stadium, Mumbai                                              351     0.450000
                                                                       442     1.000000
                                                                       49      1.000000
Dr DY Patil Sports Academy, Mumbai                                     376     0.666667
                                                                       868     1.000000
                                                                       855     1.000000
                                                                       730     0.666667
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam     585     0.750000
Eden Gardens, Kolkata                                                  451     0.000000
                                                                       217     0.000000
                                                                       1023    0.500000
                                                                       421     0.333333
Himachal Pradesh Cricket Association Stadium, Dharamsala               537     0.500000
M Chinnaswamy Stadium, Bengaluru                                       782     0.000000
                                                                       137     1.000000
MA Chidambaram Stadium, Chepauk, Chennai                               489     1.000000
                                                                       1103    0.000000
                                                                       219     0.000000
Maharashtra Cricket Association Stadium, Pune                          645     0.333333
                                                                       634     1.000000
                                                                       175     1.000000
Narendra Modi Stadium, Ahmedabad                                       162     0.666667
                                                                       938     0.000000
Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh       812     0.500000
Rajiv Gandhi International Stadium, Uppal, Hyderabad                   1110    1.000000
                                                                       1043    1.000000
                                                                       383     0.500000
Sawai Mansingh Stadium, Jaipur                                         27      0.666667
                                                                       274     1.000000
                                                                       725     0.500000
Wankhede Stadium, Mumbai                                               366     0.666667
                                                                       402     0.000000
                                                                       715     0.000000
                                                                       363     0.333333
                                                                       187     0.500000
                                                                       951     0.600000
Name: win, dtype: float64
venue
Barabati Stadium                              1119         NaN
                                              58      1.000000
                                              914     1.000000
                                              1069    0.666667
Brabourne Stadium                             126     0.750000
                                                        ...
Vidarbha Cricket Association Stadium, Jamtha  1116    0.500000
                                              387     0.000000
                                              302     0.500000
Wankhede Stadium                              223     0.666667
                                              1102    1.000000
Name: win, Length: 75, dtype: float64
venue
Arun Jaitley Stadium, Delhi                                              740          NaN
                                                                         385     1.000000
                                                                         231     0.500000
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow    298     0.666667
                                                                         1134    1.000000
                                                                         288     0.500000
Brabourne Stadium, Mumbai                                                587     0.333333
                                                                         108     1.000000
                                                                         717     1.000000
Dr DY Patil Sports Academy, Mumbai                                       638     0.666667
                                                                         733     0.000000
                                                                         81      0.500000
                                                                         821     0.666667
Eden Gardens, Kolkata                                                    958     0.500000
                                                                         690     1.000000
                                                                         720     1.000000
M Chinnaswamy Stadium, Bengaluru                                         780     1.000000
                                                                         40      1.000000
                                                                         735     0.500000
MA Chidambaram Stadium, Chepauk, Chennai                                 586     0.666667
                                                                         563     0.000000
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur       144     0.000000
Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh  822     1.000000
Maharashtra Cricket Association Stadium, Pune                            188     0.000000
                                                                         623     1.000000
                                                                         175     1.000000
Narendra Modi Stadium, Ahmedabad                                         269     1.000000
                                                                         1150    1.000000
                                                                         1125    1.000000
                                                                         95      0.666667
                                                                         389     0.500000
                                                                         335     0.600000
                                                                         162     0.500000
                                                                         894     0.571429
                                                                         138     0.625000
                                                                         1142    0.666667
                                                                         148     0.600000
                                                                         380     0.636364
                                                                         212     0.666667
                                                                         1053    0.615385
                                                                         565     0.571429
                                                                         117     0.533333
                                                                         818     0.562500
                                                                         463     0.529412
                                                                         803     0.555556
                                                                         921     0.578947
                                                                         859     0.600000
                                                                         938     0.619048
                                                                         453     0.590909
Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh         934     0.565217
Rajiv Gandhi International Stadium, Uppal, Hyderabad                     1092    1.000000
Sawai Mansingh Stadium, Jaipur                                           54      1.000000
                                                                         1066    1.000000
                                                                         753     1.000000
Wankhede Stadium, Mumbai                                                 366     0.666667
                                                                         893     1.000000
                                                                         654     1.000000
                                                                         656     1.000000
                                                                         115     0.750000
                                                                         34      0.600000
Name: win, dtype: float64
venue
Barabati Stadium                                  1069         NaN
Dr DY Patil Sports Academy                        184     0.000000
                                                  355     1.000000
                                                  234     1.000000
                                                  579     0.666667
                                                  443     0.500000
                                                  614     0.400000
                                                  365     0.333333
Eden Gardens                                      942     0.285714
Feroz Shah Kotla                                  94      0.000000
JSCA International Stadium Complex                888     1.000000
M Chinnaswamy Stadium                             120     1.000000
                                                  348     0.000000
                                                  15      0.000000
MA Chidambaram Stadium, Chepauk                   861     0.000000
                                                  704     0.000000
                                                  933     0.000000
Maharashtra Cricket Association Stadium           734     0.333333
Punjab Cricket Association Stadium, Mohali        409     0.000000
                                                  923     1.000000
                                                  497     0.500000
Rajiv Gandhi International Stadium, Uppal         323     0.333333
                                                  952     1.000000
Sawai Mansingh Stadium                            667     0.500000
                                                  543     0.000000
                                                  647     0.000000
Shaheed Veer Narayan Singh International Stadium  39      0.000000
Subrata Roy Sahara Stadium                        1073    0.000000
                                                  436     1.000000
                                                  473     1.000000
                                                  127     0.666667
                                                  663     0.500000
                                                  599     0.400000
                                                  237     0.333333
                                                  1093    0.285714
                                                  381     0.250000
                                                  988     0.222222
                                                  207     0.300000
                                                  79      0.272727
                                                  51      0.250000
                                                  384     0.230769
                                                  900     0.214286
Wankhede Stadium                                  571     0.266667
                                                  83      0.000000
                                                  591     0.500000
Name: win, dtype: float64
venue
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium   601          NaN
                                                      164     0.000000
                                                      787     0.500000
Eden Gardens                                          675     0.666667
                                                      784     0.000000
Feroz Shah Kotla                                      107     0.500000
                                                      626     1.000000